### PR TITLE
soroban-rpc: Fix test compilation problem from #516

### PR DESCRIPTION
**Pull request by 2opremio**
Fix test compilation error introduced in #516

### CODE REVIEW

File: cmd/soroban-rpc/internal/test/simulate_transaction_test.go [hunk 1]
```diff
@@ -196,9 +196,10 @@ func TestSimulateTransactionSucceeds(t *testing.T) {
 	require.NoError(t, err)
 	request := methods.SimulateTransactionRequest{Transaction: txB64}
 
+	testContractIdBytes := xdr.ScBytes(testContractId)
 	expectedXdr, err := xdr.MarshalBase64(xdr.ScVal{
 		Type:  xdr.ScValTypeScvBytes,
-		Bytes: &xdr.ScBytes(testContractId),
+		Bytes: &testContractIdBytes,
```
Comment (Shaptic) [inline cmd/soroban-rpc/internal/test/simulate_transaction_test.go:202]: fun fact: you can also do `(*xdr.ScBytes)&testContractId` to avoid a separate variable, but this is much easier to follow

**Review by Shaptic — APPROVED** [review]

**Review by tsachiherman — APPROVED** [review]
